openapi: 3.0.1
info:
  title: API for WSDLs
  description: Expose WSDL for BankService
  version: "1.0"
servers:
  - url: https://{{domain}}
paths:
  /Service.svc:
    get:
      tags:
        - bank
        - wsdl
      summary: Expose WSDL for BankService
      description: Expose ?wsdl and ?singleWsdl urls for BankService
      operationId: expose-wsdl
      parameters:
        - name: wsdl
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
        - name: singleWsdl
          in: query
          required: false
          allowEmptyValue: true
          schema:
            type: string
      responses:
        "200":
          description: WSDL document for BankService
    post:
      tags:
        - bank
        - soap
      summary: SOAP service endpoint for BankService
      description: Handle SOAP requests for BankService operations
      operationId: soap-passthrough
      requestBody:
        required: true
        content:
          text/xml:
            schema:
              type: string
      responses:
        "200":
          description: SOAP response
          content:
            text/xml:
              schema:
                type: string
        "500":
          description: SOAP fault
          content:
            text/xml:
              schema:
                type: string
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
