//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.Bank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountHolderName {
            get {
                return this.AccountHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountHolderNameField, value) != true)) {
                    this.AccountHolderNameField = value;
                    this.RaisePropertyChanged("AccountHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Bank.IBankService")]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBalance", ReplyAction="http://tempuri.org/IBankService/GetBalanceResponse")]
        decimal GetBalance(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetBalance", ReplyAction="http://tempuri.org/IBankService/GetBalanceResponse")]
        System.Threading.Tasks.Task<decimal> GetBalanceAsync(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/Deposit", ReplyAction="http://tempuri.org/IBankService/DepositResponse")]
        bool Deposit(string accountNumber, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/Deposit", ReplyAction="http://tempuri.org/IBankService/DepositResponse")]
        System.Threading.Tasks.Task<bool> DepositAsync(string accountNumber, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/Withdraw", ReplyAction="http://tempuri.org/IBankService/WithdrawResponse")]
        bool Withdraw(string accountNumber, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/Withdraw", ReplyAction="http://tempuri.org/IBankService/WithdrawResponse")]
        System.Threading.Tasks.Task<bool> WithdrawAsync(string accountNumber, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetAccountInfo", ReplyAction="http://tempuri.org/IBankService/GetAccountInfoResponse")]
        SoapClient.Bank.AccountInfo GetAccountInfo(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetAccountInfo", ReplyAction="http://tempuri.org/IBankService/GetAccountInfoResponse")]
        System.Threading.Tasks.Task<SoapClient.Bank.AccountInfo> GetAccountInfoAsync(string accountNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : SoapClient.Bank.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<SoapClient.Bank.IBankService>, SoapClient.Bank.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetBalance(string accountNumber) {
            return base.Channel.GetBalance(accountNumber);
        }
        
        public System.Threading.Tasks.Task<decimal> GetBalanceAsync(string accountNumber) {
            return base.Channel.GetBalanceAsync(accountNumber);
        }
        
        public bool Deposit(string accountNumber, decimal amount) {
            return base.Channel.Deposit(accountNumber, amount);
        }
        
        public System.Threading.Tasks.Task<bool> DepositAsync(string accountNumber, decimal amount) {
            return base.Channel.DepositAsync(accountNumber, amount);
        }
        
        public bool Withdraw(string accountNumber, decimal amount) {
            return base.Channel.Withdraw(accountNumber, amount);
        }
        
        public System.Threading.Tasks.Task<bool> WithdrawAsync(string accountNumber, decimal amount) {
            return base.Channel.WithdrawAsync(accountNumber, amount);
        }
        
        public SoapClient.Bank.AccountInfo GetAccountInfo(string accountNumber) {
            return base.Channel.GetAccountInfo(accountNumber);
        }
        
        public System.Threading.Tasks.Task<SoapClient.Bank.AccountInfo> GetAccountInfoAsync(string accountNumber) {
            return base.Channel.GetAccountInfoAsync(accountNumber);
        }
    }
}
